[webservers]
157.151.233.30

[webservers:vars]
ansible_user=ubuntu
# Use o nome exato do arquivo que você deu o chmod 400
ansible_ssh_private_key_file=../terraform/alison.sisinfo@gmail.com-2026-04-15T17_07_38.888Z_public.pem
ansible_python_interpreter=/usr/bin/python3